language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

 script:
  - for PROJECT in ./*/platformio.ini; do
       cd ${PROJECT%*/*} && platformio run && cd ../;
    done
