language: python
python:
  - "2.7"

sudo: false

install:
  - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - pip install -U platformio

script:
  - ./make && ./package

deploy:
  provider: releases
  prerelease: true
  api_key: ${GH_TOKEN}
  file_glob: true
  file: target/*
  skip_cleanup: true
  on:
    tags: true
    branch: master

