language: python
python:
  - "3.8"

sudo: false

install:
  - pip install -r ./package-ffs/requirements.txt
  - pip install -U platformio

script:
  - ./make && ./package

deploy:
  provider: releases
  prerelease: true
  api_key: ${GH_TOKEN}
  file_glob: true
  file: target/*
  skip_cleanup: true
  on:
    tags: true
    branch: master
